#!/usr/bin/env bash

stack query

cabal update

mkdir -p deps

_project="$(cat package.yaml | grep '^name:' | head -n 1 | cut -d : -f 2 | xargs)"

direct_deps() {
  cat ../package.yaml | grep '# \+ci-build-from-hackage' | cut -d '#' -f 1 | sed 's|^ *-||g' | xargs
}

pushd deps > /dev/null

cp ../$_project.cabal ./

projects() {
  for x in $(direct_deps | sort | uniq); do
    cabal install $x --dry-run | grep hw- | grep -v "^${_project}-[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+$"
  done
}

projects | sort | uniq | sed 's|^|  - |g' > stack-b.yaml

if grep '^extra-deps:$' ../stack.yaml; then
  grep '^extra-deps:$' -B 1000 ../stack.yaml | grep -v '^extra-deps:$' > stack-a.yaml
  grep '^extra-deps:$' -A 1000 ../stack.yaml | grep -v '^extra-deps:$' > stack-c.yaml
elif grep '^extra-deps: \[\]$' ../stack.yaml; then
  grep '^extra-deps: \[\]$' -B 1000 ../stack.yaml | grep -v '^extra-deps: \[\]$' > stack-a.yaml
  grep '^extra-deps: \[\]$' -A 1000 ../stack.yaml | grep -v '^extra-deps: \[\]$' > stack-c.yaml
else
  cp ../stack.yaml stack-a.yaml
  echo > stack-c.yaml
fi

if [ -s stack-b.yaml ]; then
  cat stack-a.yaml <(echo; echo 'extra-deps:') stack-b.yaml stack-c.yaml > ../stack-ci.yaml
else
  cat stack-a.yaml <(echo; echo 'extra-deps: []') stack-c.yaml > ../stack-ci.yaml
fi

popd > /dev/null
